# Generated by Django 5.1.1 on 2024-09-16 21:21

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50, verbose_name='Categoría Juego')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=50, unique=True, verbose_name='Tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50, verbose_name='Tipo usuario')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=150, verbose_name='Nombre')),
                ('username', models.TextField(max_length=150, unique=True, verbose_name='Nombre de usuario')),
                ('password', models.TextField(max_length=150, unique=True, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Correo')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CL', verbose_name='Teléfono')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.region', verbose_name='Región')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.tipousuario', verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('total', models.IntegerField(editable=False, verbose_name='Total venta')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.usuario')),
            ],
        ),
    ]
